"""
Antigravity MCP Server Subsystem.

Provides Model Context Protocol (MCP) server over JSON-RPC 2.0 stdio transport,
7 execution/lifecycle/snapshot/worker tools, Pydantic schemas, and CLI runner.
"""

from .protocol import (
    AST_SECURITY_VIOLATION,
    E2B_PROVIDER_ERROR,
    EXECUTION_TIMEOUT,
    INTERNAL_ERROR,
    INVALID_PARAMS,
    INVALID_REQUEST,
    METHOD_NOT_FOUND,
    PARSE_ERROR,
    SANDBOX_NOT_FOUND,
    SNAPSHOT_CORRUPTED,
    TOOL_ERROR,
    WORKER_SCHEDULE_ERROR,
    InternalError,
    InvalidParamsError,
    InvalidRequestError,
    JsonRpcError,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    MethodNotFoundError,
    ParseError,
    SandboxNotFoundError,
    ToolError,
    create_error_response,
    create_notification,
    create_response,
    encode_message,
    log_stderr,
    parse_jsonrpc_message,
    write_stdout,
)
from .runner import main, run_server_async
from .schemas import (
    TOOL_SCHEMAS,
    ClientInfo,
    CreateSandboxInput,
    DestroySandboxInput,
    EmbeddedResource,
    ExecuteCodeInput,
    ImageContent,
    InitializeParams,
    InitializeResult,
    ManageSnapshotInput,
    PauseSandboxInput,
    ResumeSandboxInput,
    ServerCapabilities,
    ServerInfo,
    SpawnWorkerInput,
    TextContent,
    ToolCallParams,
    ToolCallResult,
    ToolDefinition,
    ToolsListResult,
)
from .server import AntigravityMCPServer
from .tools import MCPToolRegistry

__all__ = [
    # Server & Registry
    "AntigravityMCPServer",
    "MCPToolRegistry",
    "main",
    "run_server_async",
    # Protocol Messages & Helpers
    "JsonRpcRequest",
    "JsonRpcResponse",
    "JsonRpcNotification",
    "JsonRpcError",
    "ParseError",
    "InvalidRequestError",
    "MethodNotFoundError",
    "InvalidParamsError",
    "InternalError",
    "ToolError",
    "SandboxNotFoundError",
    "parse_jsonrpc_message",
    "create_response",
    "create_error_response",
    "create_notification",
    "encode_message",
    "write_stdout",
    "log_stderr",
    # Error Codes
    "PARSE_ERROR",
    "INVALID_REQUEST",
    "METHOD_NOT_FOUND",
    "INVALID_PARAMS",
    "INTERNAL_ERROR",
    "SANDBOX_NOT_FOUND",
    "EXECUTION_TIMEOUT",
    "AST_SECURITY_VIOLATION",
    "E2B_PROVIDER_ERROR",
    "WORKER_SCHEDULE_ERROR",
    "SNAPSHOT_CORRUPTED",
    "TOOL_ERROR",
    # Schemas
    "TOOL_SCHEMAS",
    "ClientInfo",
    "ServerInfo",
    "ServerCapabilities",
    "InitializeParams",
    "InitializeResult",
    "ToolDefinition",
    "ToolsListResult",
    "ToolCallParams",
    "ToolCallResult",
    "TextContent",
    "ImageContent",
    "EmbeddedResource",
    "CreateSandboxInput",
    "ExecuteCodeInput",
    "PauseSandboxInput",
    "ResumeSandboxInput",
    "DestroySandboxInput",
    "ManageSnapshotInput",
    "SpawnWorkerInput",
]
